# -*- coding: utf-8 -*-
"""Copy of HTML Quick Styler

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1spLiTAhdg4Wp3Q83heiZCZhAaS6sVqfM
"""

!pip install -q gradio transformers

import gradio as gr
import json
import re
from datetime import datetime
from typing import Tuple, Dict, List
import random


# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
model = AutoModelForCausalLM.from_pretrained("ibm-granite/granite-3.3-2b-instruct")
messages = [
    {"role": "user", "content": "who are you?"},
]
inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,

    tokenize=True,
    return_dict=True,
    return_tensors="pt",
).to(model.device)

outputs = model.generate(**inputs, max_new_tokens=40)
print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))

from typing import Dict, List, Tuple

# ColorPaletteGenerator class has been moved to cell UOtFCegPvr5o for a consolidated Gradio app.
# Removed the redundant ColorPaletteGenerator definition from this cell.

class HTMLPageBuilder:
     """Build styled HTML pages from descriptions"""

     @staticmethod
     def extract_sections(description: str) -> List[str]:
         """Extract sections from description"""
         sections = []

         section_keywords = {
             'hero': ['hero', 'banner', 'landing'],
             'features': ['features', 'services', 'benefits'],
             'about': ['about', 'team', 'company'],
             'portfolio': ['portfolio', 'gallery', 'work', 'projects'],
             'testimonials': ['pricing', 'plans', 'cost'],
             'pricing': ['pricing', 'plans', 'cost'],
             'contact': ['contact', 'form', 'reach'],
             'footer': ['footer', 'bottom']
         }

         desc_lower = description.lower()

         # Simplified logic to prevent empty loops and for demonstration
         for section_type, keywords in section_keywords.items():
             for keyword in keywords:
                 if keyword in desc_lower:
                     sections.append(section_type)
                     break # Add only once per section type
         return list(set(sections)) # Return unique sections

     @staticmethod
     def generate_meta_tags(title: str, description: str) -> str:
         """Generate meta tags for the HTML page"""
         return f"<meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'><title>{title}</title><meta name='description' content='{description}'>"

     @staticmethod
     def generate_css(palette: Dict) -> str:
         """Generate comprehensive CSS for the page"""
         return f'''<style>
           * {{
               margin: 0;
               padding: 0;
               box-sizing: border-box;
            }}

            :root {{
               --primary: {palette['primary']};
               --secondary: {palette['secondary']};
               --accent: {palette['accent']};
               --background: {palette['background']};
               --surface: {palette['surface']};
               --text-primary: {palette['text_primary']};
               --text-secondary: {palette['text_secondary']};
               --border: {palette['border']};
                }}

                body {{
                  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                  background-color: var(--background);
                  color: var(--text-primary);
                  line-height: 1.6;
                }}
                section {{
                    padding: 40px 20px;
                    margin-bottom: 20px;
                    border-bottom: 1px solid var(--border);
                }}
                h1, h2, h3, h4, h5, h6 {{
                    color: var(--primary);
                    margin-bottom: 15px;
                }}
                p {{
                    margin-bottom: 10px;
                }}
                .hero {{
                    background-color: var(--primary);
                    color: var(--text-primary);
                    text-align: center;
                    padding: 80px 20px;
                }}
                .features {{
                    background-color: var(--surface);
                    text-align: center;
                }}
                .about {{
                    background-color: var(--background);
                }}
                .portfolio {{
                    background-color: var(--surface);
                    text-align: center;
                }}
                .contact {{
                    background-color: var(--primary);
                    color: var(--text-primary);
                    text-align: center;
                }}
                .footer {{
                    background-color: var(--secondary);
                    color: var(--text-secondary);
                    text-align: center;
                    padding: 20px;
                }}
           </style>'''

     @staticmethod
     def generate_section_html(section_type: str, palette: Dict) -> str:
         """Generate HTML for a specific section type"""
         # This is a placeholder; actual implementation would vary based on section_type
         if section_type == 'hero':
             return f"<section class='hero'><h1>Welcome to Our Site!</h1><p>A modern and responsive design.</p></section>"
         elif section_type == 'features':
             return f"<section class='features'><h2>Our Features</h2><p>Feature 1, Feature 2, Feature 3</p></section>"
         elif section_type == 'about':
             return f"<section class='about'><h2>About Us</h2><p>We are a team of passionate individuals.</p></section>"
         elif section_type == 'portfolio':
             return f"<section class='portfolio'><h2>Our Portfolio</h2><p>Recent projects display.</p></section>"
         elif section_type == 'testimonials':
             return f"<section class='testimonials'><h2>What Our Clients Say</h2><p>'Great service!' - Client Name</p></section>"
         elif section_type == 'pricing':
             return f"<section class='pricing'><h2>Pricing Plans</h2><p>Basic, Pro, Enterprise.</p></section>"
         elif section_type == 'contact':
             return f"<section class='contact'><h2>Contact Us</h2><p>Get in touch via our contact form.</p></section>"
         elif section_type == 'footer':
             return f"<section class='footer'><p>&copy; 2023 Your Company</p></section>"
         else:
             return f"<section class='{section_type}' style='background-color: {palette['surface']}; color: {palette['text_primary']}; padding: 20px;'><h1>{section_type.capitalize()} Section</h1><p>Content for {section_type}.</p></section>"


class HTMLGenerationEngine:
  """Main engine for HTML page generation"""

  @staticmethod
  def generate_page(title: str, description: str, style: str = "modern") -> Tuple[str, str]:
      """Generate complete HTML page"""

      # Generate color palette
      palette = ColorPaletteGenerator.generate_palette(style)

      # Extract sections
      sections = HTMLPageBuilder.extract_sections(description)

      # Generate meta tags and CSS
      meta_tags = HTMLPageBuilder.generate_meta_tags(title, description)
      css = HTMLPageBuilder.generate_css(palette)

      # Generate sections HTML
      sections_html = '\n\n'.join([
          HTMLPageBuilder.generate_section_html(section, palette)
          for section in sections
      ])

      # Assemble the full HTML page
      full_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    {meta_tags}
    {css}
</head>
<body>
    {sections_html}
</body>
</html>"""

      return full_html, f"HTML Page '{title}' generated successfully with {style} style."

import gradio as gr
from typing import Dict, Tuple

# Assuming HTMLGenerationEngine and HTMLPageBuilder are defined in a previous cell (e.g., YcHgLAh4oSEz)
# from YcHgLAh4oSEz import HTMLGenerationEngine, HTMLPageBuilder # This line is not needed in Colab if cell is executed before

class ColorPaletteGenerator:
  """Generate visually cohesive color palettes"""

  _palettes = {
      'modern': {
          'primary': '#667eea',
          'secondary': '#764ba2',
          'accent': '#f093fb',
          'background': '#0f172a',
          'surface': '#1e293b',
          'text_primary': '#f1f5f9',
          'text_secondary': '#cbd5e1',
          'border': '#334155'
      },
      'vibrant':{
          'primary': '#ff6b6b',
          'secondary': '#ff8e72',
          'accent': '#ffc107',
          'background': '#f8f9fa',
          'surface': '#ffffff',
          'text_primary': '#212529',
          'text_secondary': '#6c757d',
          'border': '#dee2e6'
      },
      'creative': {
          'primary': '#9b59b6',
          'secondary': '#8e44ad',
          'accent': '#e74c3c',
          'background': '#0f172a',
          'surface': '#1e293b',
          'text_primary': '#f1f5f9',
          'text_secondary': '#cbd5e1',
          'border': '#334155'
      },
      'minimal': {
          'primary': '#2c3e50',
          'secondary': '#34495e',
          'accent': '#3498db',
          'background': '#0f172a',
          'surface': '#1e293b',
          'text_primary': '#f1f5f9',
          'text_secondary': '#cbd5e1',
          'border': '#334155'
      }
  }

  @staticmethod
  def generate_palette(styler: str = "modern") -> Dict[str, str]:
      """Generate a cohesive color palette based on style"""
      return ColorPaletteGenerator._palettes.get(styler.lower(), ColorPaletteGenerator._palettes['modern'])

  @staticmethod
  def get_all_palette_names() -> List[str]:
      """Returns a list of all available color palette names."""
      return list(ColorPaletteGenerator._palettes.keys())

def get_color_suggestions(style: str) -> str:
    palette = ColorPaletteGenerator.generate_palette(style)
    markdown_output = f"### {style.capitalize()} Color Palette\n\n"
    for role, hex_code in palette.items():
        markdown_output += f"- **{role.replace('_', ' ').title()}:** <span style='color: {hex_code};'>&#9632; {hex_code}</span>\n"
    return markdown_output

with gr.Blocks() as demo:
    # Use gr.State to store the generated HTML content
    html_content_state = gr.State("")

    with gr.Tabs():

      # ============= TAB 1: Page Generator =============
       with gr.TabItem("  Generate Page"):
           with gr.Row():
               with gr.Column(scale=1):
                   gr.Markdown("###  Page Details")

                   page_title = gr.Textbox(
                       label="Page Title",
                       value="Modern portfolio website",
                       lines=1
                   )

                   page_description = gr.Textbox(
                       label="Page Description & Sections",
                       value="Hero section with welcome message, features list with 3 items, about section, portfolio gallery, testimonials, contact form",
                       lines=4
                   )

                   color_style = gr.Dropdown(
                       label="Color Style",
                       choices=ColorPaletteGenerator.get_all_palette_names(),
                       value="modern"
                   )
                   generate_button = gr.Button("Generate HTML Page", size="lg", variant="primary")

           status_msg = gr.Markdown("", visible=False)

           def generate_and_store_html(title, description, style):
               generated_html, status_message = HTMLGenerationEngine.generate_page(title, description, style)
               # Only store the generated HTML and update status message
               return generated_html, status_message

           generate_button.click(
               generate_and_store_html,
               inputs=[page_title, page_description, color_style],
               outputs=[html_content_state, status_msg]
           )


      # ============== TAB 2: Preview ==============
       with gr.TabItem("Live Preview"):
           gr.Markdown("### Preview Generated Page")

           preview_output = gr.HTML(value="<p style='text-align: center; color:#fff; padding:40px;'>Generate a page first.</p>")
           raw_html_display = gr.Code(label="Raw HTML Code", language="html", interactive=False, lines=10, value="")

           preview_button = gr.Button("Load Preview", size="lg", variant="primary")

           def show_preview(html_text):
               if not html_text.strip():
                   empty_msg = "<p style='text-align: center; color:#fff; padding:40px;'>No HTML provided.</p>"
                   return empty_msg, empty_msg # Return for both outputs
               return html_text, html_text # Return the same HTML for both rendered and raw

           preview_button.click(
               show_preview,
               inputs=[html_content_state],
               outputs=[preview_output, raw_html_display]
           )

      # ============== TAB 3: Color Palettes ==============
       with gr.TabItem("Color Palettes"):
           gr.Markdown("### Explore Color Schemes")

           with gr.Row():
               style_selector = gr.Radio(
                   ColorPaletteGenerator.get_all_palette_names(), # Use new method
                   value="modern",
                   label="Choose Style",
               )

               palette_btn = gr.Button(" Get Palette", size="lg", variant="primary")

           palette_display = gr.Markdown()

           palette_btn.click(
               get_color_suggestions,
               inputs=[style_selector],
               outputs=[palette_display]
           )

      # ============== TAB 4: Templates ==============
       with gr.TabItem("Templates"):
           gr.Markdown("### Quick Templates")

           with gr.Row():
               with gr.Column():
                   gr.Markdown("""
                   #### Portfolio website
                   Hero, Portfolio Gallery, About, Contact, Footer
                   """)
                   portfolio_btn = gr.Button("Use Template", size="sm")

                   def load_portfolio():
                       return ("Portfolio Website",
                               """Hero section with welcome banner,
                               portfolio gallery with 6 items, about section,
                               contact form, footer""",
                               "modern")

                   portfolio_btn.click(load_portfolio, outputs=[page_title,
                                                          page_description, color_style])

               with gr.Column():
                   gr.Markdown("""
                   #### SaaS Landing Page
                   Hero, Features, pricing, testimonials, CTA, Footer
                   """)

      # =============== TAB 5: Guide ==============
       with gr.TabItem("Guide"):
           gr.Markdown("""
           # HTML Quick_Styler Guide

           ## How It Works

           ### 1.Enter Details
           - **Title:** Page name
           - **Description:** Sections you want
           - **Color Style:** pick a theme

           ### 2. Automatic Detection
           The tool recognizes  these keywords:
           - 'here' / 'banner' -> Hero section
           - 'features' / 'services' / -> Features Grid
           - 'about' / 'team' -> About Section
           - 'portfolio' / 'gallery' -> Portfolio
           - 'pricing' / 'plans' / 'cost' -> Pricing plans
           - 'contact' / ' form' ->contact form
           - 'footer' -> Footer
           """)

print("\n HTML Quick-Styler Advanced Ready!\n")
demo.launch(share=True, show_error=True, show_api=False)

import gradio as gr
from typing import Dict, Tuple

class ColorPaletteGenerator:
  """Generate visually cohesive color ipalettes"""

  @staticmethod
  def generate_palette(styler: str = "modern") -> Dict[str, str]:
      """Generate a cohesive color palette based on style"""

      palettes = {
          'modern': {
              'primary': '#667eea',
              'secondary': '#764ba2',
              'accent': '#f093fb',
              'background': '#0f172a',
              'surface': '#1e293b',
              'text_primary': '#f1f5f9',
              'text_secondary': '#cbd5e1',
              'border': '#334155'
          },
          'vibrant':{
              'primary': '#ff6b6b',
              'secondary': '#ff8e72',
              'accent': '#ffc107',
              'background': '#f8f9fa',
              'surface': '#ffffff',
              'text_primary': '#212529',
              'text_secondary': '#6c757d',
              'border': '#dee2e6'
          },
          'creative': {
              'primary': '#9b59b6',
              'secondary': '#8e44ad',
              'accent': '#e74c3c',
              'background': '#0f172a',
              'surface': '#1e293b',
              'text_primary': '#f1f5f9',
              'text_secondary': '#cbd5e1',
              'border': '#334155'
          },
          'minimal': {
              'primary': '#2c3e50',
              'secondary': '#34495e',
              'accent': '#3498db',
              'background': '#0f172a',
              'surface': '#1e293b',
              'text_primary': '#f1f5f9',
              'text_secondary': '#cbd5e1',
              'border': '#334155'
          }
      }
      return palettes.get(styler.lower(), palettes['modern'])

def get_color_suggestions(style: str) -> str:
    palette = ColorPaletteGenerator.generate_palette(style)
    markdown_output = f